// Generated by CoffeeScript 1.12.7
(function() {
  var app, express, parseColors, std_map;

  express = require('express');

  app = express();

  std_map = require('./std_map.js');

  app.use(express["static"]('files'));

  app.get('/', function(req, res) {
    var K, Size, Step, answ, colors;
    K = req.query.K;
    Step = req.query.Step;
    Size = req.query.Size;
    colors = [req.query.Color1, req.query.Color2, req.query.Color3, req.query.Color4, req.query.Color5, req.query.Color6, req.query.Color7, req.query.Color8];
    if (K === void 0 || Size === void 0 || Step === void 0) {
      return res.sendFile(__dirname + '/index.html');
    } else {
      answ = std_map(parseFloat(K), parseFloat(Step), parseInt(Size), parseColors(colors));
      if (answ !== "error") {
        console.log(answ);
        return res.sendFile(__dirname + '/result.html');
      } else {
        return res.sendFile(__dirname + '/index.html');
      }
    }
  });

  app.listen(3000, function() {
    return console.log('Example app listening on port 3000!');
  });

  parseColors = function(colors) {
    var color, i, len, ret;
    ret = [];
    for (i = 0, len = colors.length; i < len; i++) {
      color = colors[i];
      ret.push(parseInt("0x" + color + "FF"));
    }
    return ret;
  };

}).call(this);
